Feature: MW_RSA_CISL_1
  The MW_RSA_CISL_1 routing rules testing

  Scenario Outline: Routing rule simulation for <testName>
    Given I have a valid access token
    When I set headers to
      | name                | value     |
      | simulate-routing    | true      |
      | subscriptionCountry | <country> |
    And I <method> /RSA/cisl1/<resourcePath>
    Then response code should be 200
    And response body should contain "backend":"<backend>"
    And response body should contain "ruleName":"<ruleName>"

    Examples:
      | testName                                            | country | method  | resourcePath                                        | backend       | ruleName                                                                                                  |
      # ABS (default)
      | Get assignmenttariffs on ABS                        | DEU     | GET     | assignments/0001/assignmenttariffs                  | BCK_ABS       | default                                                                                                   |
      | Get assistanceCases on ABS                          | DEU     | GET     | assistancecases/0001                                | BCK_ABS       | default                                                                                                   |
      | Get assistanceCases/assignments on ABS              | DEU     | GET     | assistancecases/0001/assignments/0001               | BCK_ABS       | default                                                                                                   |
      | POST expertreports on ABS                           | DEU     | POST to | assistancecases/0001/assignments/0001/expertreports | BCK_ABS       | default                                                                                                   |
      | Get assistanceCases/assignments/notes on ABS        | DEU     | GET     | assistancecases/0001/assignments/0001/notes         | BCK_ABS       | default                                                                                                   |
      | POST assistanceCases/assignments/notes on ABS       | DEU     | POST to | assistancecases/0001/assignments/0001/notes         | BCK_ABS       | default                                                                                                   |
      | PUT assistanceCases/assignments/status on ABS       | DEU     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_ABS       | default                                                                                                   |
      | Get bills/documents on ABS                          | DEU     | GET     | bills/0001/documents/0001                           | BCK_ABS       | default                                                                                                   |
      | Get parties on ABS                                  | DEU     | GET     | parties                                             | BCK_ABS       | default                                                                                                   |
      | Get parties by id on ABS                            | DEU     | GET     | parties/0001                                        | BCK_ABS       | default                                                                                                   |
      | Get assignmentInfo on ABS                           | DEU     | GET     | search/assignmentInfo                               | BCK_ABS       | default                                                                                                   |
      | Get bills on ABS                                    | DEU     | GET     | search/bills                                        | BCK_ABS       | default                                                                                                   |
      | Get serviceproviders on ABS                         | DEU     | GET     | search/serviceproviders                             | BCK_ABS       | default                                                                                                   |
      | PUT assistanceCases/assignments/status for ESP      | ESP     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_ABS       | default                                                                                                   |
      # Unity CZE
      | Get assignmenttariffs on Unity CZE                  | CZE     | GET     | assignments/0001/assignmenttariffs                  | BCK_Unity_CZE | GET_assignments__assignmentId__assignmenttariffs_to_BCK_Unity_CZE_cty_CZE                                 |
      | Get assistanceCases on Unity CZE                    | CZE     | GET     | assistancecases/0001                                | BCK_Unity_CZE | GET_assistancecases__assistanceCaseId__to_BCK_Unity_CZE_cty_CZE                                           |
      | Get assistanceCases/assignments on Unity CZE        | CZE     | GET     | assistancecases/0001/assignments/0001               | BCK_Unity_CZE | GET_assistancecases__assistanceCaseId__assignments__assignmentId__to_BCK_Unity_CZE_cty_CZE                |
      | Get assistanceCases/assignments/notes on Unity CZE  | CZE     | GET     | assistancecases/0001/assignments/0001/notes         | BCK_Unity_CZE | GET_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_CZE_cty_CZE          |
      | Get parties on BCK_Unity_CZE                        | CZE     | GET     | parties                                             | BCK_Unity_CZE | GET_parties_to_BCK_Unity_CZE_cty_CZE                                                                      |
      | Get parties by id on BCK_Unity_CZE                  | CZE     | GET     | parties/0001                                        | BCK_Unity_CZE | GET_parties__partyId__to_BCK_Unity_CZE_cty_CZE                                                            |
      | Get assignmentInfo on BCK_Unity_CZE                 | CZE     | GET     | search/assignmentInfo                               | BCK_Unity_CZE | GET_search_assignmentInfo_to_BCK_Unity_CZE_cty_CZE                                                        |
      | POST expertreports on BCK_Unity_CZE                 | CZE     | POST to | assistancecases/0001/assignments/0001/expertreports | BCK_Unity_CZE | POST_assistancecases__assistanceCaseId__assignments__assignmentId__expertreports_to_BCK_Unity_CZE_cty_CZE |
      | POST assistanceCases/assignments/notes on Unity CZE | CZE     | POST to | assistancecases/0001/assignments/0001/notes         | BCK_Unity_CZE | POST_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_CZE_cty_CZE         |
      | PUT assistanceCases/assignments/status on Unity CZE | CZE     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_Unity_CZE | PUT_assistancecases__assistanceCaseId__assignments__assignmentId__status_to_BCK_Unity_CZE_cty_CZE         |
      | Get serviceproviders on Unity CZE                   | CZE     | GET     | search/serviceproviders                             | BCK_Unity_CZE | GET_search_serviceproviders_to_BCK_Unity_CZE_cty_CZE                                                      |
      # Unity RUS
      | Get assignmenttariffs on Unity RUS                  | RUS     | GET     | assignments/0001/assignmenttariffs                  | BCK_Unity_RUS | GET_assignments__assignmentId__assignmenttariffs_to_BCK_Unity_RUS_cty_RUS                                 |
      | Get assistanceCases on Unity RUS                    | RUS     | GET     | assistancecases/0001                                | BCK_Unity_RUS | GET_assistancecases__assistanceCaseId__to_BCK_Unity_RUS_cty_RUS                                           |
      | Get assistanceCases/assignments on Unity RUS        | RUS     | GET     | assistancecases/0001/assignments/0001               | BCK_Unity_RUS | GET_assistancecases__assistanceCaseId__assignments__assignmentId__to_BCK_Unity_RUS_cty_RUS                |
      | Get assistanceCases/assignments/notes on Unity RUS  | RUS     | GET     | assistancecases/0001/assignments/0001/notes         | BCK_Unity_RUS | GET_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_RUS_cty_RUS          |
      | Get parties on BCK_Unity_RUS                        | RUS     | GET     | parties                                             | BCK_Unity_RUS | GET_parties_to_BCK_Unity_RUS_cty_RUS                                                                      |
      | Get parties by id on BCK_Unity_RUS                  | RUS     | GET     | parties/0001                                        | BCK_Unity_RUS | GET_parties__partyId__to_BCK_Unity_RUS_cty_RUS                                                            |
      | Get assignmentInfo on BCK_Unity_RUS                 | RUS     | GET     | search/assignmentInfo                               | BCK_Unity_RUS | GET_search_assignmentInfo_to_BCK_Unity_RUS_cty_RUS                                                        |
      | POST expertreports on BCK_Unity_RUS                 | RUS     | POST to | assistancecases/0001/assignments/0001/expertreports | BCK_Unity_RUS | POST_assistancecases__assistanceCaseId__assignments__assignmentId__expertreports_to_BCK_Unity_RUS_cty_RUS |
      | POST assistanceCases/assignments/notes on Unity RUS | RUS     | POST to | assistancecases/0001/assignments/0001/notes         | BCK_Unity_RUS | POST_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_RUS_cty_RUS         |
      | PUT assistanceCases/assignments/status on Unity RUS | RUS     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_Unity_RUS | PUT_assistancecases__assistanceCaseId__assignments__assignmentId__status_to_BCK_Unity_RUS_cty_RUS         |
      | Get serviceproviders on Unity RUS                   | RUS     | GET     | search/serviceproviders                             | BCK_Unity_RUS | GET_search_serviceproviders_to_BCK_Unity_RUS_cty_RUS                                                      |
      # Unity THA
      | Get assignmenttariffs on Unity THA                  | THA     | GET     | assignments/0001/assignmenttariffs                  | BCK_Unity_THA | GET_assignments__assignmentId__assignmenttariffs_to_BCK_Unity_THA_cty_THA                                 |
      | Get assistanceCases on Unity THA                    | THA     | GET     | assistancecases/0001                                | BCK_Unity_THA | GET_assistancecases__assistanceCaseId__to_BCK_Unity_THA_cty_THA                                           |
      | Get assistanceCases/assignments on Unity THA        | THA     | GET     | assistancecases/0001/assignments/0001               | BCK_Unity_THA | GET_assistancecases__assistanceCaseId__assignments__assignmentId__to_BCK_Unity_THA_cty_THA                |
      | Get assistanceCases/assignments/notes on Unity THA  | THA     | GET     | assistancecases/0001/assignments/0001/notes         | BCK_Unity_THA | GET_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_THA_cty_THA          |
      | Get parties on BCK_Unity_THA                        | THA     | GET     | parties                                             | BCK_Unity_THA | GET_parties_to_BCK_Unity_THA_cty_THA                                                                      |
      | Get parties by id on BCK_Unity_THA                  | THA     | GET     | parties/0001                                        | BCK_Unity_THA | GET_parties__partyId__to_BCK_Unity_THA_cty_THA                                                            |
      | Get assignmentInfo on BCK_Unity_THA                 | THA     | GET     | search/assignmentInfo                               | BCK_Unity_THA | GET_search_assignmentInfo_to_BCK_Unity_THA_cty_THA                                                        |
      | POST expertreports on BCK_Unity_THA                 | THA     | POST to | assistancecases/0001/assignments/0001/expertreports | BCK_Unity_THA | POST_assistancecases__assistanceCaseId__assignments__assignmentId__expertreports_to_BCK_Unity_THA_cty_THA |
      | POST assistanceCases/assignments/notes on Unity THA | THA     | POST to | assistancecases/0001/assignments/0001/notes         | BCK_Unity_THA | POST_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_THA_cty_THA         |
      | PUT assistanceCases/assignments/status on Unity THA | THA     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_Unity_THA | PUT_assistancecases__assistanceCaseId__assignments__assignmentId__status_to_BCK_Unity_THA_cty_THA         |
      | Get serviceproviders on Unity THA                   | THA     | GET     | search/serviceproviders                             | BCK_Unity_THA | GET_search_serviceproviders_to_BCK_Unity_THA_cty_THA                                                      |
      # Unity VNM
      | Get assignmenttariffs on Unity VNM                  | VNM     | GET     | assignments/0001/assignmenttariffs                  | BCK_Unity_THA | GET_assignments__assignmentId__assignmenttariffs_to_BCK_Unity_THA_cty_VNM                                 |
      | Get assistanceCases on Unity VNM                    | VNM     | GET     | assistancecases/0001                                | BCK_Unity_THA | GET_assistancecases__assistanceCaseId__to_BCK_Unity_THA_cty_VNM                                           |
      | Get assistanceCases/assignments on Unity VNM        | VNM     | GET     | assistancecases/0001/assignments/0001               | BCK_Unity_THA | GET_assistancecases__assistanceCaseId__assignments__assignmentId__to_BCK_Unity_THA_cty_VNM                |
      | Get assistanceCases/assignments/notes on Unity VNM  | VNM     | GET     | assistancecases/0001/assignments/0001/notes         | BCK_Unity_THA | GET_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_THA_cty_VNM          |
      | Get parties on Unity VNM                            | VNM     | GET     | parties                                             | BCK_Unity_THA | GET_parties_to_BCK_Unity_THA_cty_VNM                                                                      |
      | Get parties by id on Unity VNM                      | VNM     | GET     | parties/0001                                        | BCK_Unity_THA | GET_parties__partyId__to_BCK_Unity_THA_cty_VNM                                                            |
      | Get assignmentInfo on Unity VNM                     | VNM     | GET     | search/assignmentInfo                               | BCK_Unity_THA | GET_search_assignmentInfo_to_BCK_Unity_THA_cty_VNM                                                        |
      | POST expertreports on Unity VNM                     | VNM     | POST to | assistancecases/0001/assignments/0001/expertreports | BCK_Unity_THA | POST_assistancecases__assistanceCaseId__assignments__assignmentId__expertreports_to_BCK_Unity_THA_cty_VNM |
      | POST assistanceCases/assignments/notes on Unity VNM | VNM     | POST to | assistancecases/0001/assignments/0001/notes         | BCK_Unity_THA | POST_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Unity_THA_cty_VNM         |
      | PUT assistanceCases/assignments/status on Unity VNM | VNM     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_Unity_THA | PUT_assistancecases__assistanceCaseId__assignments__assignmentId__status_to_BCK_Unity_THA_cty_VNM         |
      | Get serviceproviders on Unity VNM                   | VNM     | GET     | search/serviceproviders                             | BCK_Unity_THA | GET_search_serviceproviders_to_BCK_Unity_THA_cty_VNM                                                      |
      # Polanet
      | Get assignmenttariffs on Polanet                    | POL     | GET     | assignments/0001/assignmenttariffs                  | BCK_Polanet   | GET_assignments__assignmentId__assignmenttariffs_to_BCK_Polanet_cty_POL                                   |
      | Get assistanceCases on Polanet                      | POL     | GET     | assistancecases/0001                                | BCK_Polanet   | GET_assistancecases__assistanceCaseId__to_BCK_Polanet_cty_POL                                             |
      | Get assistanceCases/assignments on Polanet          | POL     | GET     | assistancecases/0001/assignments/0001               | BCK_Polanet   | GET_assistancecases__assistanceCaseId__assignments__assignmentId__to_BCK_Polanet_cty_POL                  |
      | POST expertreports on Polanet on Polanet            | POL     | POST to | assistancecases/0001/assignments/0001/expertreports | BCK_Polanet   | POST_assistancecases__assistanceCaseId__assignments__assignmentId__expertreports_to_BCK_Polanet_cty_POL   |
      | Get assistanceCases/assignments/notes on Polanet    | POL     | GET     | assistancecases/0001/assignments/0001/notes         | BCK_Polanet   | GET_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Polanet_cty_POL            |
      | POST assistanceCases/assignments/notes on Polanet   | POL     | POST to | assistancecases/0001/assignments/0001/notes         | BCK_Polanet   | POST_assistancecases__assistanceCaseId__assignments__assignmentId__notes_to_BCK_Polanet_cty_POL           |
      | PUT assistanceCases/assignments/status on Polanet   | POL     | PUT     | assistancecases/0001/assignments/0001/status        | BCK_Polanet   | PUT_assistancecases__assistanceCaseId__assignments__assignmentId__status_to_BCK_Polanet_cty_POL           |
      | Get parties on Polanet                              | POL     | GET     | parties                                             | BCK_Polanet   | GET_parties_to_BCK_Polanet_cty_POL                                                                        |
      | Get parties by id on Polanet                        | POL     | GET     | parties/0001                                        | BCK_Polanet   | GET_parties__partyId__to_BCK_Polanet_cty_POL                                                              |
      | Get assignmentInfo on Polanet                       | POL     | GET     | search/assignmentInfo                               | BCK_Polanet   | GET_search_assignmentInfo_to_BCK_Polanet_cty_POL                                                          |
      | Get serviceproviders on Polanet                     | POL     | GET     | search/serviceproviders                             | BCK_Polanet   | GET_search_serviceproviders_to_BCK_Polanet_cty_POL                                                        |
      
